version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7.22
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_root_password
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=epiquery
    networks:
      - local 

  mssql:
    container_name: mssql
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y 
      - SA_PASSWORD=YourV3ryStrong!Passw0rd
    networks:
      - local 

  sfdc:
    build: ./mock-salesforce
    volumes:
      - ./mock-salesforce:/var/app
      - /var/big_pants
    ports: 
      - "80:80" 
    networks:
      - local 
  
networks:
  local:
    driver: bridge
