#! /usr/bin/env bash
exec 2>&1
# enable ACLs
ps aux | grep epistream\.coffee | grep -v grep | awk '{printf("%s\n", $2)}' | xargs kill -SIGUSR2 > /dev/null 2>&1
curl -s -H "jwt-test: 1" http://${EPI_TEST_SERVER}:8080/epiquery1/mssql/test/acl_tests.mustache
# disable ACLs
ps aux | grep epistream\.coffee | grep -v grep | awk '{printf("%s\n", $2)}' | xargs kill -SIGUSR1 > /dev/null 2>&1
