#! /usr/bin/env bash
exec 2>&1
# enable ACLs
ps aux | grep epistream\.coffee | grep -v grep | awk '{printf("%s\n", $2)}' | xargs kill -SIGUSR2 > /dev/null 2>&1
curl -s http://${EPI_TEST_SERVER}:8080/diagnostic | jq '.aclsEnabled'
# disable ACLs
ps aux | grep epistream\.coffee | grep -v grep | awk '{printf("%s\n", $2)}' | xargs kill -SIGUSR1 > /dev/null 2>&1
curl -s http://${EPI_TEST_SERVER}:8080/diagnostic | jq '.aclsEnabled'
# enable ACLs
ps aux | grep epistream\.coffee | grep -v grep | awk '{printf("%s\n", $2)}' | xargs kill -SIGUSR2 > /dev/null 2>&1
curl -s http://${EPI_TEST_SERVER}:8080/diagnostic | jq '.aclsEnabled'
# leave the ACLs disabled for the other tests
ps aux | grep epistream\.coffee | grep -v grep | awk '{printf("%s\n", $2)}' | xargs kill -SIGUSR1 > /dev/null 2>&1
